# Generated by Django 5.0.2 on 2024-03-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comments_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_author_on',
            new_name='post_author',
        ),
    ]
