# Generated by Django 5.0.2 on 2024-03-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_post_author_on_comments_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-commented_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='post_author',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='date_commented',
            new_name='commented_date',
        ),
    ]
